// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewsllxorouuczohiegdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3c2xseG9yb3V1Y3pvaGllZ2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NjE5MzgsImV4cCI6MjA3MTIzNzkzOH0.At-np4gX1A6h4mBNWsPXSaAvb3wwrQiMOyXDKqaXMoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});